### ISSUE TITLE
Investigate repo structure - split content from engine?

### ISSUE THREAD

**Issue by ahpook** [lyraproj/lyra#172]
**Is your feature request related to a problem? Please describe.**
Right now there is a tight coupling between the engine and the plugins / content, because they're all in the same repo. It might be beneficial to split these out so that they can iterate more quickly and independently.

**Describe the solution you'd like**
There's a few possibilities:
1. keep everything in the mono repo
2. create one separate 'content' / 'plugins' repo that is distinct from the engine but has all the plugins
3. create a separate repo for every plugin

Let's investigate the pros/cons of each and make a decision so we can get things set up for contributors.

**Comment by jdwelch** [comment]
+1 to one keeping content in the 'lyra' repo until there's so much as to be unwieldy; until we have an easy way to install the CLI & operator from packages, everyone will have a clone of the repo anyway, so might as well include everything needed to get started in one place.

**Comment by jdwelch** [comment]
fwiw, there's already a variety of supporting repos (that contain the workflow engine, evaluator, etc) that allows each of those pieces to move independently

**Comment by thallgren** [comment]
-1 to keeping content in the 'lyra' repo but I'm all in favour of having a repo that brings everything in using a go.mod file and makes it easy to build using a Makefile. As @jdwelch points out, we already have a well established and functional approach where things move independently. I would very much like us to use that approach for plugins too rather than sticking things that ought to be separate into one repository. It should be as simple as separating an umbrella build repository from the modules that contains the actual artefacts. By doing so, we can create different umbrellas for different purposes and languages. I for one, want to be able to build and test just a small subset of it all when I do changes to the framework. The speed of the "edit, debug, edit again"-cycle is very important and even with the no longer embedded plugins, that cycle is somewhat hampered already.

To me, the whole idea of Lyra goes beyond cloud provisioning. The core wf engine can be used for a variety of things. Why not create a really good Go replacement for a Makefile for instance? Only half kidding. I'm not saying that we should do things like that now, or even ever, but I'd hate to see us package things up so that ideas like that becomes impossible to elaborate on just because we didn't had the time to structure our moving parts correctly to begin with.

We're building a micro-services architecture. We must take that seriously. I fear that what might seem convenient today (the mega-repo) will become very inconvenient very soon. If we think it's hard to split things up now, then rest assured, it's nothing compared to what it will become later on.

**Comment by scottyw** [comment]
Agree with @thallgren and would probably pick option 2 - one big content repo - which I think moves us in the right direction while keep it easy for a content developer to grab a single repo and get going.

@thallgren just merged a working example of seamlessly pulling plugins from other repos. If you use master as of now, the identity service and puppet plugins come from separate repos transparently using "go mod". I think if we can make sure the first-time use workflow is "pull the repo and run a single make command" then we can afford to separate code into repos as we wish.

**Comment by ahpook** [comment]
Awesome work yall 🎉

**Comment by ahpook** [comment]
Whoops, I mistakenly closed it because I thought this was done.

**Comment by scottyw** [comment]
Here's a concrete proposal:

* Move all Terraform-based content and the supporting bridge into a single separate repo with a guide on how to integrate new TF providers
* Keep our "native" AWS content in the Lyra repo as an real-world example of how to create content directly
* Create some more example Lyra content in the Lyra repo as further illustration of Lyra's capabilities and for testing purposes
* Move the "modelled" AWS content out of Lyra into it's own repo for posterity but remove it from our build and documentation - this work helped us understand the right way to create content but was superceded by the "native" variant from bullet 2
* Ensure that the user can still check out just the Lyra repo and have all TF content be pulled down as dependencies and built transparently i.e. you only need to clone the "Terraform content" repo if you want to contribute there

What are your thoughts?

**Comment by ahpook** [comment]
Sounds great, especially that last point.

**Comment by scottyw** [comment]
TF content is now here: https://github.com/lyraproj/terraform-bridge. That's pulled and built into Lyra automatically.

The AWS content is staying where it is until we get some solid example content in as per #196.

The examples continue to be improved via #188.

**Comment by ahpook** [comment]
Things have evolved in the past couple of months so I'm reopening to incorporate discussion of the goplugin ecosystem.

Pro option 1, anti option 3: In the long run, that approach will lead to a severely bloated and monolithic repository with a constantly increasing number of dependencies. Plugins should reside in their own repositories and to have their own go.mod file. As Lyra grows, and the number of plugins increases, it will get very cumbersome to always have the baggage of everything, even if you just want to use a small subset.  Lyra is already fairly fine-grained and assembled from several repos.

Pro option 3, anti option 1: "repo bloat" isn't a problem we have, because there are 4 plugins and IMO it'd be managable up to the low hundreds. I think there are advantages to having them in 1 place. (a) discoverability by new users, if people want to make their own they can see the examples and change them inline, request PR reviews as dhollinger has done, and have them available by default (b) if all known plugins are part of the core build, changes to internals of lyra components which break plugins will cause a broken build, and (c) Putting every plugin in a separate repo under its author's github namespace would create fragmentation before it even began, and we'd need more scaffolding (a registry, namespaces, etc) to compensate for it.

Given all that it seems like option 2 is the best; IMO we should make a lyraproj/lyra-plugins repo and move things there, but include it as a dependency at build time. This will address:
- the repo bloat/coupling problem because the code will be split out from the core engine,
- the breaking-change problem because they will be pulled in as part of the build rather than requiring each plugin to test against lyra changes independently
- the fragmentation problem because they'll all be in one place under the project namespace not individual github accts,


Relates to #189

**Comment by thallgren** [comment]
Having one repo for all plugins seems counter intuitive given that many of them have very different purposes. Some contribute content, others don't. Some questions related to that:

1. Do we move the identity service to the lyra-plugins repo?
2. Should the terraform-bridge be moved to this repo so that we provide two solutions for terraform?
3. What about the yaml-workflow and puppet-workflow plugins?
4. What about plugins written in other languages? A repo is very often tailored for one language (a go.mod file at the root, a package.json, etc.)

Some disadvantages we will run into by keeping all plugins in one repository:

**Size of the deliverable**
Some plugins are huge and have dependency graphs that are several pages long. The terraform bridge alone contributes more than 300Mb of storage space. We will force gigabytes of data onto a user that perhaps only wants to use a fraction of what we provide.

**All or nothing releases**
The go module infrastructure uses the git SHA in dependencies. Moving all plugins into one repo means that they all share the same SHA. We can no longer release them individually. That in turn means that when we move forward, we will run into QA-issues with build and test times of all plugins just because one of them is modified. It consumes a lot of resources and creates a churn for everything whenever one piece of the puzzle has a problem. That in turn tends to slow down the pace for new releases and bug-fixes because the task of creating a new release is just too big.

**Cumbersome bug fixing**
When working with bug-fixes on plug-in and relying on `go run`, each iteration will build all plugins. That means that the "tweak, build, test" cycle gets much longer. The time will increase for each new plugin that we add and it's already too long to be comfortable.

**Cumbersome to contribute to**
If someone wants to contribute a new plugin or create PRs for an existing one, they are forced to build and download all dependencies for all plugins just to get going. They must build and test all plugins in order to get the PR green. At present, it takes about 20 minutes to discover that you've made a mistake, and then another 20 before you know that you fixed it.

**Code reuse**
Maintaining purposeful repositories means that the code can be reused in other projects. We have a very well defined model for the Lyra plugins that third-party tooling may want to make use of. It's not unthinkable that people may want to write plugins that add to the functionality that our plugins provide.

**Comment by dhollinger** [comment]
I'm with @thallgren on this after thinking some more about it. Option 2 would end up having the same eventual problem as option 1 plus some more if plugins are written in multiple languages.

I really don't have much more to add that @thallgren didn't already mention

**Comment by ahpook** [comment]
I guess I'd thought of this as being scoped only to _ecosystem_ plugins : currently terraform, foobernetes, the "example", and the contributed heroku one. These have the characteristics (AFAIK) that they teach lyra about new kinds of external resources to manage (not things like identity service which must exist for anything to work), and they must be written in Go (AFAIK we do not support adding new non-Golang resource types, nor is this a goal). 

The thing I'm most concerned about if they get split out all over the place is this: how do we make them available to end-users with a minimum of friction?

**Comment by thallgren** [comment]
We can actually add new resource types using Puppet-DSL too and I've already done some work on #219 although that is put on hold for now. I think it's important that we recognize that what we have is a model that is designed to be polyglot which means that we are free to explore such options, should we so desire. It would be unfortunate if we ditched that ability because we chose a bad model for distribution.

I think it is @ahpook's last question: "how do we make them available to end-user with a minimum of friction" that must be answered. That's what we should be discussing in depth and I think that there are several options available that we might want to exploit. Here are two that relies fairly heavily on [go mod](https://blog.golang.org/using-go-modules) (which we already use for all modules).

1. Let us view github.com (and perhaps additional repositories) as a "forge" and rely on the go.mod mechanism to find things for us there. This requires a go runtime but perhaps we can make Lyra contain that? With a go runtime available, the Lyra loader could load (build and run) plugins on demand.

2. The go echo system makes it very easy to create a custom configuration that can be precompiled. In essence, you create a go.mod file, put it in a repo, and you're ready to use it provided that your're happy using `go run`. Creating a brew bottle from that is more work but I can't imagine that it would be very hard to provide a command that would do just that by appointing to a custom configuration. We could provide any number of such configurations, tailored for specific combinations of plugins. My knowledge about brew is very limited, but surely it must be possible to define sub-modules and dependencies?

Documentation of all plugins and how they fit together can be provided using [godoc](https://godoc.org/golang.org/x/tools/cmd/godoc) in server mode. We will need to provide amper package documentation for all packages. If that's not enough, it's probably fairly easy to generate a TOC in markdown format that appoints readme files of the individual repositories.

**Comment by thallgren** [comment]
Here's a concrete proposal for how I think we should work with Lyra and all content providing plugins (referred to as "providers" below).

This proposal takes into consideration that we want to:

- make the user's initial contact with Lyra as smooth as possible.
- let the user install only what's needed.
- release each provider separately.
- make it easy for organizations to create and use their own providers (public or private)
- be able to work with lyra without spending time on building and testing "everything"
- scale lyra indefinitely with new providers
- be honest about the vision to create a flexible, micro service based, infrastructure.

In order to accomplish all of the above, we should:

1. remove all dependencies to providers from lyra except the foobernetes one.
2. as a consequence of #1, remove the making of those providers from the lyra Makefile.
3. instead, let each provider be dependent on Lyra.
4. let each provider reside in a repository of its own.
5. let each provider have a makefile with builds, tests, and package (creates a brew bottle)
6. perhaps create an additional package named `lyra-all` that is dependent of all providers (this maps to option <span>#</span>2).

A user using Lyra with terraform would install using `brew install lyra-terraform`. This would install both the lyra CLI and the terraform provider. If we do <span>#</span>6, then the user would also be able to do `brew install lyra-all` which would install lyra with all providers made available from us.

**Comment by scottyw** [comment]
A separate brew package for each provider doesn't really seem right to me. That seems like something we should be managing within the app (`lyra module ...`). I wonder if we could achieve most of steps 1-6 without using brew as the package manager, which doesn't feel quite right to me since the user could end up with rather a lot of packages installed.

Perhaps we could replace step 5 with support for downloading and building the providers? Or we could ship a list of released providers and their URLs? McCabe had a plan to create a hosted endpoint that would act as a registry of released providers and we could take steps towards that goal without necessarily going as far as hosting.

**Comment by thallgren** [comment]
How common do we expect it to be that a typical user works with more than one or two providers? I'm a bit reluctant to a `lyra module ...` that installs things on the local host because that turns Lyra into a package manager.

**Comment by scottyw** [comment]
Ah, that's the key question: I figured users would have many (10s or 100s) but you figure single figures. That changes things for me either way. If it's single figures then I'm more comfortable with brew.

**Comment by dhollinger** [comment]
We also have to consider how you'd add providers to the operator in Kubernetes. I can't imagine building my own operator container or having to update it manually anytime I added a new provider as good UX for the user.

Not to mention that (I'd assume) there are users in both Linux and Windows land that would also like Lyra packages, which kind of throws brew as the only install option out the window. Despite being available for Linux, few enterprises allow installations of software on the system outside of the package manager proper.
