### ISSUE TITLE
Destroy 

### ISSUE THREAD

**Issue by kenazk** [lyraproj/lyra#38]
**Is your feature request related to a problem? Please describe.**
I want the ability to destroy infrastructure that I have created. 

**Describe the solution you'd like**
I want the ability to destroy infrastructure that I have created: 
- CLI - `lyra destroy` or some likeness that destroys previously created resources
- Kubernetes - When the CRD object associated with the workflow is deleted, it should trigger the same destroy workflow

**Describe alternatives you've considered**
None.

**Additional context**
Couple other behavioral suggestions: 
- Destroy should happen in a sensible order that respects implicit dependencies (e.g. VPC and subnet) 
- Resources that have been previously created, but subsequently removed from the manifest should be destroyed via garbage collection or similar mechanism

**Comment by scottyw** [comment]
Relates to #45

**Comment by thallgren** [comment]
#45 adds a delete command. The term was chosen because we've used it frequently in our discussions and it's also what D refers to in CRUD. I'm a bit concerned if we want to rename the command to "destroy".

"The infrastructure has been destroyed" sounds to me like it's now completely broken. Smashed to pieces. "The infrastructure has been deleted" on the other hand, sounds like it has been removed and no longer exists.

Is the term "destroy" commonly used by other tools in the domain?

**Comment by jdwelch** [comment]
I don't feel terribly strongly about it, but I like the connotation with 'destroy' that the action you're taking is serious and irrevocable. 'Delete' is certainly more common, so I'm happy to go with that.

**Comment by kenazk** [comment]
@thallgren - Is there a version of this where you can destroy all resources that have been created by Lyra vs the provided workflow? Just thinking about the case where someone is iteratively developing their infra by creating one workflow at a time, then borks it, and wants to blow away all resources created.

**Comment by kenazk** [comment]
Ok. Thanks @thallgren. Let's hold off for now. 

Anything else we need to close this feature?
