### ISSUE TITLE
Package Format for Workflows 

### ISSUE THREAD

**Issue by kenazk** [lyraproj/lyra#41]
## **Is your feature request related to a problem? Please describe.**
I want to package one or more Workflows up and submit it to Lyra to be consumed through Kubernetes so that I can produce consumable and reusable Workflows. Inspired by Helm for UX. 

### Proposed package architecture 
- metadata.yaml which includes name of the package, description, version information, dependencies(?)
- data.yaml for external hiera data 
- workflows directory containing all Workflows to be packaged up together

Outputs an artifact in some archive format. 

### Consuming packages
Workflow packages can be referenced for consumption in several ways: 
- Loadpath or well-known location
- URL to the package 
- Direct

### Operations 
Lyra should support the following operations: 
- Apply - Deploy the package  
- Upgrade - Upgrade the version of the package
- Delete  - Delete the package
- Package - Create the package
- Generate - Create a sample package structure 

### Deferred
I would posit that first class repo support should be delayed to a later implementation.

**Comment by kenazk** [comment]
Would like your thoughts here @scottyw @jdwelch in terms of the Operations. Apply, Package, and Generate seem like no brainers to me. However, Upgrade and Delete imply that we are maintaining state of the packages themselves which feels wrong to me. 

Particularly because the whole collection of Workflows should be packaged together as a single CRD. Which also means that our terminology may need revisiting. Does 1 Workflow = 1 Workflow CRD? Or can you package N workflows = 1 Workflow CRD?

**Comment by scottyw** [comment]
I think we should continue with a single Workflow CRD but support many Workflow resources, even multiple references to the same Lyra workflow. It feels like Helm might already provide the functionality we need. Perhaps we want a tool to generate a Helm chart e.g. "I want to deploy workflow A with parameters X, workflow A with parameters Y and workflow B with parameters Z, please make me a Helm chart"?

**Comment by jdwelch** [comment]
Some more "so that"s, specifically for _consumers_ of workflow packages, to inform what kinds of metadata to capture:
+ "so that I know if a workflow will work with my Lyra version" (eg 'appVersion')
+ "so that I know who to contact with questions" (eg 'maintainer')
+ "so that I know if I am allowed to use this thing my project" (eg 'licence')
+ "so that I can keep track of changes to a workflow over time" (eg 'version')
+ "so that I know what parameters are available to be configured at runtime" (a sample data file and/or object spec)
+ "so that I know where the thing came from" (eg a signed artefact)

**Comment by jdwelch** [comment]
Here's my first pass at a package structure. It's pretty much what you'd expect:

```
my-project
├── README.md
├── metadata.yaml
├── deploy.yaml
├── values.yaml
└── workflows
    └──my-project-default.pp
```

and what that looks like with `lyra create` at the command line:

[![asciicast](https://asciinema.org/a/222726.svg)](https://asciinema.org/a/222726)

**Comment by scottyw** [comment]
@kenazk I think your 1 and 2 there are broader than Kube.

1 is about versioning of workflows which we currently don't support. As you edit a workflow and re-apply we will "garbage collect" any infrastructure you've removed but we do not have a concept in Lyra of workflow versioning. You'd just have two versions of your workflow called `compute-v1.pp` and `compute-v2.pp`.

2 is a big one because `my-application` is a sort of implicit workflow wrapping up the inner 3 workflows. You could also do this explicitly to arbitrary depth.

**Comment by kenazk** [comment]
Good point @scottyw. I agree that this is a separate set of work from simply creating a packaging structure for the workflow(s). I'll add another ticket.

**Comment by jdwelch** [comment]
Ah, OK, yeah, I just thought we were talking about the structure not the lifecycle, which I need to have more of a think on :)

**Comment by kenazk** [comment]
@jdwelch can you provide one sentence description of what each of these things are? I get README and values, but what about deploy and metadata?

**Comment by jdwelch** [comment]
https://github.com/jdwelch/lyra/blob/ux/41/docs/package-format.md

**Comment by kenazk** [comment]
Excellent! Do you want a separate UX repo? Or do you want to commit to this one?

**Comment by jdwelch** [comment]
I was gonna see how far we get with branches here until it gets too much to deal with

**Comment by jdwelch** [comment]
Updated the spec a bit: https://github.com/lyraproj/lyra/blob/ux/41/docs/package-format.md

Your thoughts, @kenazk ?

**Comment by scottyw** [comment]
> Let me clarify what I was trying to disambiguate. Say I have 3 Workflows that I want to deploy at once using one K8s object spec in a package called `my-application`:
> 
> ```
> my-application
> ├── README.md
> ├── metadata.yaml
> ├── deploy.yaml
> ├── values.yaml
> ├── workflows
>     └──compute.pp
>     └──network.pp
>     └──storage.pp
> ```
> Great! I deploy it and my whole app comes online. Now, if I want to deploy the same my-application from the CLI, I expect at some point Lyra to support:
> `lyra apply my-application`

I've been thinking about this more. I said above that `my-application` was a sort of implicit workflow. On reflection I think it literally *is* a workflow.

I figure there are two scenarios here. In one case, I have some workflows like `compute` and `network` that I want to bring together into a meaningful, parameterizable app. We already support that via workflows building on other workflows (see #115). That's our mechanism for combining things and showing the relationships between them, and supports being run from the CLI as you describe. Adding `package` in this case is just a different (and potentially less expressive) way of capturing the same concept.

In the other case, I have a Kube app that is bigger than Lyra. I am deploying some containers and volumes and all the rest and as a part of that bigger picture I want to deploy one or more Lyra Workflow resources. Helm already solves this problem I think. From a Lyra POV we have no visibility into the wider needs of the app outside of the Lyra-specific parts anyway.

Either way I'm not sure we need packaging as a concept. I'm making a distinction here between packaging of apps and deployment of Lyra itself as described in #49 which I reckon we do still need.

**Comment by thallgren** [comment]
A comment regarding the `my-projects-actions.ts` file. There are a few things that we need to address:

1. Nodejs is not capable of running a TypeScript file. It must be transpiled into JavaScript.
2. The TypeScript compiler will not be able to transpile it without a slew of options that resolves dependencies.
3. In order for nodejs to run a JS file, it must resolve dependencies. Both the `lyra-workflow` npm package and generated resource types that it makes use of.
4. The author of TS/JS files are very likely use a development environment using npm and possibly an IDE.

The normal way for a TS/JS author to work is by creating a npm project. Such a project will contain a package.json where all dependencies are described. An `npm install` in the package will ensure that all dependencies are resolved. We can of course auto-generate such a package with some default dependency hierarchy when we find the `my-projects-actions.ts` but I don't think we solve any real life problems by doing so because it has already been done to achieve bullet number 4 in the list.

Working with typescript I'm more and more convinced that the Lyra loader needs to either find npm packages or npm projects on disk, and then possibly files within such projects that contains manifests to be loaded. Question is, how do we accomplish that? When contemplating the answer to that question, we should also consider that there will be similar problems with many other languages. Most languages have well established project hierarchies and package formats. If we want Lyra to be serious about being polyglot,  then it must handle that in a good way.

Ideas around this are very welcome.

**Comment by scottyw** [comment]
I can see two distinct but related issues here. There's the question of packaging up a bunch of (say) TypeScripts files and dependencies in a way that Lyra can successfully load them as a single plugin. I think your comment @thallgren is in that direction.

I read the original ticket description as proposing something like Puppet modules which is used to combine one or more workflows and corresponding hiera data into a shareable unit. That might be many yaml files or binaries or a mixture, with additional metadata like author and licence and such. I don't think that's really about only Kubernetes, it's a general Lyra-wide question

I think those things are related but at different levels. The latter is about sharing and reuse while the former is about raw ability to function. Maybe we should cut these into separate issues?

Go binaries don't suffer the first problem because each is a self-contained file that we can just execute and expect it to work. YAML and Puppet DSL files aren't directly executed at all. For TS, JS, Ruby, Python and maybe others, we need to know how to configure the execution environment. What files need to be compiled, what dependency resolution tools need to be run and things like that.

@markfuller and I were talking through some thoughts on the that, and had been chatting about a "lyra.yaml" similar to ".travis.yaml" that describes how to build and run a plugin. @markfuller pointed out that this is awfully like a workflow. I think that's really smart. What if we say that, by convention, we will look in each plugin (sub-dir, zip file, tar file etc.) for a "lyra.yaml" workflow? If found we will execute that workflow to build and run the plugin? Use Lyra to bootstrap Lyra!

**Comment by thallgren** [comment]
@scottyw I'm thinking about this from a TS/JS developers perspective. It seems somewhat awkward that they should have to write a workflow in YAML, just to be able to run another workflow written in TS/JS. For the first use-case, I think they ideally would like to:

1. Set up my development environment (likely with [npx gts init](https://github.com/google/ts-style) or similar).
2. Use npm to install the lyra-workflow module.
3. Generate needed types using the Lyra generate command (this step would likely be formalized under the script tag in `package.json`).
4. Enter the cycle of creating my TS/JS manifests, applying them, altering them, applying again, etc.

For the second use-case, a JS/TS developer commonly share modules using the npm global website or github (npm can install directly from GitHub). Being polyglot, I think Lyra needs to consider this domain as well as the language, because it's equally important.

**Comment by scottyw** [comment]
@thallgren Oh, I get you. Yeah, you talked about a more native experience above and I didn't really twig the significance of it. Totally agree.

**Comment by thallgren** [comment]
When looking at #80 and #115, I would like to propose that in addition to what is proposed here, Lyra itself should also have a "workflows" directory. It makes no sense having files with a '.pp', or '.yaml' extension residing under "plugins" directory. I also think that the term "plugins" is unfortunate as it associates user-facing things with one possible choice of RPC implementation. What if Lyra (and applications) had this:
```
lyra
  ├──workflows
  ├──types
     └──Aws.pp
     └──...
  ├──handlers
     ├──goplugins
        └──aws             # this is former "goplugin-aws" with prefix removed
        └──puppetdsl
        └──...
     ├──rest
        └──identity        # something that activates REST communication with a configured remote service
```
If we then decide that all names and locations in the directory structure are significant, so that 'handlers/goplugins/aws' *must* provide handlers for the 'Aws' typeset, then the need for pre-loading will go away. Instead, the loader can load the handler on demand the first time it is requested. The current loader framework is already capable of this.
@scottyw @markfuller what's your opinion on this?

**Comment by scottyw** [comment]
@thallgren I really like that. I also agree that the current approach has emerged from the evolution of the product, isn't really right and should be changed asap.

**Comment by jdwelch** [comment]
+1 to @thallgren's plan.

**Comment by ahpook** [comment]
We've got the repository / workflow structure set up; this is a distinct problem from how to package/share workflows in the ecosystem. Still need to consider that but it's not 0.1 blocker.
