### ISSUE TITLE
Prototype UX for dual interfaces: CLI & K8s Object Spec 

### ISSUE THREAD

**Issue by kenazk** [lyraproj/lyra#47]
We will support multiple interfaces for using Lyra, starting with a CLI version and a K8s object spec. 

We should do some investigation on how these interfaces will work with each other. Additionally, we may want the CLI options for deploying the controller to Kubernetes. 

Supports #37.

**Comment by jdwelch** [comment]
I'm interpreting this to mean:

"As a [user of lyra†], I need to apply workflows directly from my workstation to the target infrastructure platform(s) so that
	+ The feedback loop is short"
	+ I don't need to faff with k8s for 'hello, world'"

"As a [user of lyra‡], I want to apply workflows via kubectl so that
	* I get the benefits of a k8s object lifecycle"
	* [etc]"

Accurate?
---
† = I think the 'producer' of workflows is the primary user of the Lyra CLI for these operations.
‡ = And here, the 'consumer' of workflows is more likely to instantiate workflows someone else has made available to them in their cluster(s).

**Comment by kenazk** [comment]
Yes, thanks for articulating it that way. How does Lyra support both of those interfaces with a common set of functionality?

**Comment by jdwelch** [comment]
Workflow: https://www.lucidchart.com/invitations/accept/21dab304-bd9b-4ac9-b227-fc4478683942

**Comment by jdwelch** [comment]
![Workflow](https://www.lucidchart.com/publicSegments/view/72001786-0248-478d-9cdc-1c2558b5a5c2/image.png)

**Comment by jdwelch** [comment]
What specific question do you have?

**Comment by jdwelch** [comment]
![Workflow](https://www.lucidchart.com/publicSegments/view/72001786-0248-478d-9cdc-1c2558b5a5c2/image.png)

**Comment by kenazk** [comment]
I'm less concerned with the CLI workflow. I'm thinking more about the K8s
workflow. How do you want to structure the K8s object spec? This is
what @scottyw started with:

apiVersion: lyra.example.com/v1alpha1
kind: Workflow
metadata:
  name: sample2-workflow
spec:
  workflowName: "sample2"
  data:
    foo: kubeFooooo2
    bar: kubeBaaaar
    baz: kubeBaaaaz
  refreshTime: 35

If that seems fine, then I think it's just documenting the prescribed
workflow in the repo.

Kenaz

**Comment by scottyw** [comment]
@kenazk I think we're using the same library both ways. Lyra won't *need* to run in Kube but we'll likely eventually support it for those who want it.
