### ISSUE TITLE
Validation logic for admission for k8s objects

### ISSUE THREAD

**Issue by kenazk** [lyraproj/lyra#50]
Supports #37 

The Lyra k8s controller needs some validation logic on the K8s object spec to ensure that the object being passed to it conforms to the required input spec.

**Comment by markfuller** [comment]
Some work done here in https://github.com/lyraproj/lyra/pull/123

[CRD has some input validation](https://github.com/lyraproj/lyra/blob/bf08638f71de0b2fb73b4d00f6f939244e93087c/k8s/lyra_v1alpha1_workflow_crd.yaml#L34-L46) but this is limited, for example we cannot (or do not) check that the workflow exists (lyra doesn't support listing workflows, if it did perhaps we could explore [https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#validatingadmissionwebhook](validatingadmissionwebhook)) 

Relating to this but more for #94, we do recover from panics in lyra and publish the status (adding [additionalPrinterColumns](https://github.com/lyraproj/lyra/blob/bf08638f71de0b2fb73b4d00f6f939244e93087c/k8s/lyra_v1alpha1_workflow_crd.yaml#L18 to expose the status and info to `kubectl get workflows`)

```
➜  go-strcase git:(master) ✗ kubectl get workflows
NAME               WORKFLOWNAME      AGE   LYRASTATUS      STATUSINFO
sample2-workflow   sample2notreal   23h   RetryingApply   Unable to find definition for activity sample2notreal
```

(note: this will retry ad infinitum - if the operator is running - because there is no, for example, MISSING_WORKFLOW error code, it is just a general panic that is caught)

**Comment by ahpook** [comment]
This is close enough to done to close - if there's more sophisticated validation that users want, we can add more tickets later.
