### ISSUE TITLE
Remove "Puppet DSL" support from Lyra

### ISSUE THREAD

**Issue by jdwelch** [lyraproj/lyra#91]
**Is your feature request related to a problem? Please describe.**
Having a chat with @scottyw this morning led to the idea that it's time to have a conversation about dropping Puppet DSL support in Lyra. Here are some reasons, in no particular order:

+ What we're calling "Puppet DSL" bears only passing resemblance to what current users of Puppet actually interact with; it's increasingly disingenuous to conflate the two; they share some syntax conventions, but conceptually and semantically, only passing resemblance.
+ Now that we're able to author workflows in YAML, a major use case for Puppet (declarative workflow actions) is solved elsewhere.
+ New users coming from other cloud native tooling will not expect or be familiar with Puppet, so choosing something more widespread (TypeScript, Go) will ease the learning curve.

**Describe the solution you'd like**
Remove Puppet as a supported language for authoring workflows and invest in TypeScript as the preferred method for authoring the imperative bits of workflows and their actions.

**Comment by thallgren** [comment]
While I'm all in favor of this in a long term perspective, I think we should hold off acting on it until we have a fully functional replacement (i.e. TypeScript) that is acceptable to our intended users. YAML is not a replacement since no imperative code cannot be entered there. In essence, invest in TypeScript first, make it fully functional, then remove Puppet DSL.

**Comment by jdwelch** [comment]
Oh, that's another point I meant to add: I wonder if it's worse to get folks using Puppet then yank it versus wait for TypeScript and only support declarative action until then. @kenazk? You know how much fun it is to remove capabilities after the fact...

**Comment by thallgren** [comment]
Keep in mind that having a language capable of imperative evaluation around is pretty good during development too. I've used it several times to write fake providers, providing debugging output, etc.
Another point making is that if it's very hard to remove after the fact, then that is probably because it gained some popularity. I know we don't expect that but it's really an argument against removing it if we're afraid that it's going to happen.

**Comment by scottyw** [comment]
I would probably accept the short term loss of functionality that comes with removing Puppet DSL before TS is ready. I think the time gap will be relatively small and I think usability improves if we can focus first time users on a single familiar experience. 

Users could potentially still write imperative actions with Go? Most of our examples emphasize declarative use cases too.

We could potentially take 2 steps, by first removing the pp examples and docs but retaining the functionality for development purposes.

**Comment by jdwelch** [comment]
Oh, that's a reasonable idea. I'd definitely be in favour of pulling out the examples at this points.

**Comment by thallgren** [comment]
@kenazk, I don't agree that we have the same concerns with TS/JS. It's a general purpose language and won't be doing anything that "looks and feels" like it. We will run TS/JS using the nodejs VM. What we will provide there is something that makes it easy to express the workflow and it's activities using well-known TS/JS constructs.

**Comment by kenazk** [comment]
Sounds good. I do have to say that trying to figure out whether to put on my Ruby hat or Puppet hat when writing imperative code all around feels bad.

**Comment by ahpook** [comment]
We'd expect the user journey to start with yaml and move to typescript (as you need to get more complex and add things like actions), which we want to emphasise in the docs and examples. There's not a high maintenance burden to leaving puppet in, though, and there is some utility in having the golang puppet parser actively used. So i'm in favour of leaving it as-is.
