### ISSUE TITLE
Logging and status updates 

### ISSUE THREAD

**Issue by kenazk** [lyraproj/lyra#95]
As a Lyra user, I want more verbose logging and status updates so that I can see what is happening when I apply my Workflow both from the CLI as well as from Kubernetes.

**Comment by thallgren** [comment]
One of the more prominent technology advantages with Lyra is that it is built using a modern micro-services approach. This gives us a number of advantages where polyglot services is one, and the ability to distribute the services in different hosts, is another. Micro-services are however somewhat challenging when it comes to logging. Especially if there's a desire to also mix the logs with logs from external providers (such as k8s). We are currently using hclog since it's sufficient and helpful during development of plug-ins. Hclog however, doesn't scale and it is not intended to address the challenges with micro-services logging.

I recommend reading this blog. It explains many of the challenges and gives good advice on how to address them: https://logz.io/blog/logging-microservices/

**Comment by scottyw** [comment]
I read "logging" as referring to user interface messages rather than error/info/debug style logging that is primarily for troubleshooting?

@kenazk Do you think there's anything more to do here?

**Comment by ahpook** [comment]
Got some improvements in this today with #181 - gonna close this one and move on.
